# syntax=docker/dockerfile:1.7-labs

# Build the application from source
FROM golang:1.21 AS build-stage

WORKDIR /app

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -o /pejuang-tani-srv

# Deploy the application binary into a lean image
FROM alpine:3.20.3 AS build-release-stage

WORKDIR /

COPY --from=build-stage /pejuang-tani-srv .

ENTRYPOINT ["/pejuang-tani-srv"]

LABEL org.opencontainers.image.source https://github.com/stnDinus/uas_ppb_server
